language: node_js
node_js:
    - 13

cache: npm

# Tell travis not to clone with depth, this way we avoid the error: "shallow update not allowed" pushing to dokku server
git:
  depth: false

install: npm install

# Skip while tests are not available
script: skip

before_deploy:
    - openssl aes-256-cbc -K $encrypted_90e0bc3da5e6_key -iv $encrypted_90e0bc3da5e6_iv -in .travis/dokku.pem.enc -out .travis/dokku.pem -d
    - git config --local http.sslcert .travis/dokku.pem
deploy:
    # Deploy to dokku server
    provider: script
    # Remember to configure the env variables from .env.sample in the Dokku server using dokku config:set
    # Besides "dokku config:set NPM_CONFIG_PRODUCTION=false" is required to avoid dokku to prune devDependencies required for the start command (cross-env and nuxt-ts)
    # See: https://devcenter.heroku.com/articles/nodejs-support#package-installation
    script: bash .travis/deploy.sh
    skip_cleanup: true
    on:
        branch: hydrogen
