const TYPES = {
    UserService: Symbol.for('UserService'),
    ToastService: Symbol.for('ToastService'),
    ModalService: Symbol.for('ModalService'),
    HistoryService: Symbol.for('HistoryService'),
    HttpService: Symbol.for('HttpService'),
    AuthApiService: Symbol.for('AuthApiService'),
    CommunitiesApiService: Symbol.for('CommunitiesApiService'),
    HashtagsApiService: Symbol.for('HashtagsApiService'),
    CategoriesApiService: Symbol.for('CategoriesApiService'),
    PostsApiService: Symbol.for('PostsApiService'),
    NotificationsApiService: Symbol.for('NotificationsApiService'),
    ModerationApiService: Symbol.for('ModerationApiService'),
    FollowsApiService: Symbol.for('FollowsApiService'),
    ConnectionsApiService: Symbol.for('ConnectionsApiService'),
    EnvironmentService: Symbol.for('EnvironmentService'),
    LocalizationService: Symbol.for('LocalizationService'),
    StringTemplateService: Symbol.for('StringTemplateService'),
    StorageService: Symbol.for('StorageService'),
    LinkPreviewService: Symbol.for('LinkPreviewService'),
    UtilsService: Symbol.for('UtilsService'),
    MediaService: Symbol.for('MediaService'),
    NotificationsService: Symbol.for('NotificationsService'),
    LoggingService: Symbol.for('LoggingService'),
    ThemeService: Symbol.for('ThemeService'),
    WindowService: Symbol.for('WindowService'),
    NavigationService: Symbol.for('NavigationService'),
    UserPreferencesService: Symbol.for('UserPreferencesService'),
    PostUploaderService: Symbol.for('PostUploaderService'),
    BootstrapService: Symbol.for('BootstrapService'),
    VideoPlaybackService: Symbol.for('VideoPlaybackService'),
};

export { TYPES };
