const TYPES = {
    UserService: Symbol.for('UserService'),
    ToastService: Symbol.for('ToastService'),
    ModalService: Symbol.for('ModalService'),
    HistoryService: Symbol.for('HistoryService'),
    HttpService: Symbol.for('HttpService'),
    AuthApiService: Symbol.for('AuthApiService'),
    CommunitiesApiService: Symbol.for('CommunitiesApiService'),
    CategoriesApiService: Symbol.for('CategoriesApiService'),
    PostsApiService: Symbol.for('PostsApiService'),
    NotificationsApiService: Symbol.for('NotificationsApiService'),
    FollowsApiService: Symbol.for('FollowsApiService'),
    EnvironmentService: Symbol.for('EnvironmentService'),
    LocalizationService: Symbol.for('LocalizationService'),
    StringTemplateService: Symbol.for('StringTemplateService'),
    StorageService: Symbol.for('StorageService'),
    UtilsService: Symbol.for('UtilsService'),
    LoggingService: Symbol.for('LoggingService'),
    ThemeService: Symbol.for('ThemeService'),
    WindowService: Symbol.for('WindowService'),
    NavigationService: Symbol.for('NavigationService'),
    UserPreferencesService: Symbol.for('UserPreferencesService'),
    BootstrapService: Symbol.for('BootstrapService'),
};

export { TYPES };